#!/bin/bash
# Sync personal settings to ~/.claude and clean up artifacts from the old
# copy-based sync. Commands, skills, agents, and hooks are no longer copied —
# they ship via the plugin (/plugin install mays@dotfiles).

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLAUDE_DIR="$HOME/.claude"

echo "Cleaning up files installed by the old copy-based sync..."

rm -f "$CLAUDE_DIR"/commands/{custom-,cmd-}*.md
rm -f "$CLAUDE_DIR"/commands/{cleanup,code-review,commit-push-pr,extreme-code-quality-review,fix-merge-conflict,quick-commit,remember,repo-init,scratchpad,take-notes,test-and-fix}.md
rm -f "$CLAUDE_DIR"/hooks/{block-destructive-git,block-hardcoded-secrets,post-edit-format}.md
rm -f "$CLAUDE_DIR"/agents/extreme-code-quality-review.md

for name in code-architect code-review extreme-code-quality-review gemini-image-generator serverless-aws verify-app writing-style; do
  target="$CLAUDE_DIR/skills/$name"
  # Symlinks are marketplace-managed, not ours
  [ -d "$target" ] && [ ! -L "$target" ] && rm -rf "$target"
done
rm -rf "$CLAUDE_DIR/skills/scripts"

echo "Syncing settings..."
cp "$SCRIPT_DIR/settings.json" "$CLAUDE_DIR/settings.json"

# Maintain the managed block in ~/.claude/CLAUDE.md: standards lookup for every
# code review (including the native /code-review) plus git conventions that
# replaced the old /quick-commit and /commit-push-pr commands.
CLAUDE_MD="$CLAUDE_DIR/CLAUDE.md"

# macOS ships bash 3.2, which mis-parses an apostrophe inside a quoted heredoc
# when the heredoc sits inside $( ). Build the block via a temp file instead.
BLOCK_FILE="$(mktemp)"
trap 'rm -f "$BLOCK_FILE"' EXIT
cat > "$BLOCK_FILE" <<'EOF'
<!-- mays:managed:start -->
When reviewing code, check whether the repo has `.claude/standards.md` (generated by /distill-standards). If it exists, apply its rules as review criteria and cite the specific rule in each finding.

When the user corrects the same kind of mistake twice in one session, offer once to record the pattern as a rule in `.claude/standards.md` under `## Manual` (create the file with just that section if it doesn't exist). Hard threshold: two corrections of the same pattern, at most one offer per session, and drop it silently if declined — never nag.

Git conventions:

- Commit messages use conventional commits format (feat:, fix:, chore:, docs:, refactor:, test:) with the subject under 72 characters, summarizing the why.
- Never stage or commit `.env*`, credential files, `*.pem`, or `*.key`.
- Never push directly to main/master.
- PR descriptions get a 1-3 bullet summary and a test plan section.

Code comments: default to none. A comment must carry a fact the code cannot — a why, an invariant, or a warning. One line is the default; more only to record a decision and its constraints, never to restate code or narrate the diff.

Writing: apply the `ste-writing` skill to everything you write for me — chat answers, reports, plans, summaries, artifacts — not only text aimed at other people. Load the skill for document-length work (artifact, README, runbook, design doc, PR body) and for any rewrite request. Otherwise apply these directly:

- Answer first: the result in 1-3 sentences or at most 5 bullets, then detail. Delete context I will not act on.
- No preamble, no recap of what you just did, no narrating your own structure.
- Never quote my code or file contents back to me — cite `file.ts:42` instead.
- Backtick exact names, paths, flags, and values. Use numbers, not "several" or "much faster".
- Active voice, named actor, present tense for behavior.
- Cut hedges and intensifiers: "very", "simply", "just", "might possibly". A bare "should" is "must" or "we recommend".
- One idea per sentence, under 25 words — 20 for an instruction.

This cuts sentences, not substance. Keep every caveat, uncertainty, risk, and disagreement, and keep contractions and directness. Never drop articles or actors to save space. Essays and blog posts use `writing-style` instead. Code, logs, and error text stay verbatim.
<!-- mays:managed:end -->
EOF
BLOCK="$(cat "$BLOCK_FILE")"
echo "Updating managed block in ~/.claude/CLAUDE.md..."
if grep -qsF "mays:managed:start" "$CLAUDE_MD"; then
  BLOCK="$BLOCK" perl -0777 -i -pe 's/<!-- mays:managed:start -->.*?<!-- mays:managed:end -->/$ENV{BLOCK}/s' "$CLAUDE_MD"
else
  # Drop the bare standards one-liner an older sync may have written
  [ -f "$CLAUDE_MD" ] && perl -i -ne 'print unless /generated by \/distill-standards/' "$CLAUDE_MD"
  printf '\n%s\n' "$BLOCK" >> "$CLAUDE_MD"
fi

echo ""
echo "Done. Install the plugin from within Claude Code if you haven't:"
echo "  /plugin marketplace add stevenmays/dotfiles"
echo "  /plugin install mays@dotfiles"
