#!/bin/bash
# Sync personal settings to ~/.claude and clean up artifacts from the old
# copy-based sync. Commands, skills, agents, and hooks are no longer copied —
# they ship via the plugin (/plugin install mays@dotfiles).

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLAUDE_DIR="$HOME/.claude"

echo "Cleaning up files installed by the old copy-based sync..."

rm -f "$CLAUDE_DIR"/commands/{custom-,cmd-}*.md
rm -f "$CLAUDE_DIR"/commands/{cleanup,code-review,commit-push-pr,extreme-code-quality-review,fix-merge-conflict,quick-commit,remember,repo-init,scratchpad,take-notes,test-and-fix}.md
rm -f "$CLAUDE_DIR"/hooks/{block-destructive-git,block-hardcoded-secrets,post-edit-format}.md
rm -f "$CLAUDE_DIR"/agents/extreme-code-quality-review.md

for name in code-architect code-review extreme-code-quality-review gemini-image-generator serverless-aws verify-app writing-style; do
  target="$CLAUDE_DIR/skills/$name"
  # Symlinks are marketplace-managed, not ours
  [ -d "$target" ] && [ ! -L "$target" ] && rm -rf "$target"
done
rm -rf "$CLAUDE_DIR/skills/scripts"

echo "Syncing settings..."
cp "$SCRIPT_DIR/settings.json" "$CLAUDE_DIR/settings.json"

# Maintain the managed block in ~/.claude/CLAUDE.md: standards lookup for every
# code review (including the native /code-review) plus git conventions that
# replaced the old /quick-commit and /commit-push-pr commands.
CLAUDE_MD="$CLAUDE_DIR/CLAUDE.md"
BLOCK=$(cat <<'EOF'
<!-- mays:managed:start -->
When reviewing code, check whether the repo has `.claude/standards.md` (generated by /distill-standards). If it exists, apply its rules as review criteria and cite the specific rule in each finding.

Git conventions:

- Commit messages use conventional commits format (feat:, fix:, chore:, docs:, refactor:, test:) with the subject under 72 characters, summarizing the why.
- Never stage or commit `.env*`, credential files, `*.pem`, or `*.key`.
- Never push directly to main/master.
- PR descriptions get a 1-3 bullet summary and a test plan section.
<!-- mays:managed:end -->
EOF
)
echo "Updating managed block in ~/.claude/CLAUDE.md..."
if grep -qsF "mays:managed:start" "$CLAUDE_MD"; then
  BLOCK="$BLOCK" perl -0777 -i -pe 's/<!-- mays:managed:start -->.*?<!-- mays:managed:end -->/$ENV{BLOCK}/s' "$CLAUDE_MD"
else
  # Drop the bare standards one-liner an older sync may have written
  [ -f "$CLAUDE_MD" ] && perl -i -ne 'print unless /generated by \/distill-standards/' "$CLAUDE_MD"
  printf '\n%s\n' "$BLOCK" >> "$CLAUDE_MD"
fi

echo ""
echo "Done. Install the plugin from within Claude Code if you haven't:"
echo "  /plugin marketplace add stevenmays/dotfiles"
echo "  /plugin install mays@dotfiles"
