#!/bin/bash
# SessionStart hook: inject the repo's distilled standards so code is written
# compliant on the first pass instead of repaired at review time.
top=$(git rev-parse --show-toplevel 2>/dev/null) || exit 0
standards="$top/.claude/standards.md"
[ -f "$standards" ] || exit 0

echo "This repo has distilled coding standards (.claude/standards.md, generated by /distill-standards). Apply them while writing code, not just when reviewing:"
echo
cat "$standards"
exit 0
